name: Thomas
author: WIMSE
baseurl:
description:
project: thomasfors.se

domain_site:
domain_email:
domain_password:

github_account:
github_password:

flickr_account:
flickr_password:

embed_account:
embed_password:

disqus: thomas-fors
disqus_username: thomas_fors
disqus_password: wimsethomas1

port: 2000
envir: devel

email: info@wimse.se
location: 42°2'16"N   70°12'47"W


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
